[package]
edition = "2018"
name = "stm32f0"
version = "0.15.1"
authors = ["Adam Greig <adam@adamgreig.com>", "stm32-rs Contributors"]
description = "Device support crates for STM32F0 devices"
repository = "https://github.com/stm32-rs/stm32-rs"
readme = "README.md"
keywords = ["stm32", "svd2rust", "no_std", "embedded"]
categories = ["embedded", "no-std"]
license = "MIT/Apache-2.0"

[dependencies]
critical-section = { version = "1.0", optional = true }
cortex-m = "0.7.6"
cortex-m-rt = { version = ">=0.6.15,<0.8", optional = true }
vcell = "0.1.3"

[package.metadata.docs.rs]
features = ['critical-section', 'rt', 'stm32f0x0', 'stm32f0x1', 'stm32f0x2', 'stm32f0x8']
default-target = "thumbv6m-none-eabi"
targets = []

[features]
default = ["critical-section", "rt"]
rt = ["cortex-m-rt/device"]
stm32f0x0 = []
stm32f0x1 = []
stm32f0x2 = []
stm32f0x8 = []
