///Register `MTLISR` reader
pub struct R(crate::R<MTLISR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MTLISR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MTLISR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MTLISR_SPEC>) -> Self {
        R(reader)
    }
}
///Field `Q0IS` reader - Queue interrupt status This bit indicates that an interrupt has been generated by Queue. To reset this bit, read ETH_MTLQICSR register to identify the interrupt cause and clear the source.
pub type Q0IS_R = crate::BitReader<bool>;
impl R {
    ///Bit 0 - Queue interrupt status This bit indicates that an interrupt has been generated by Queue. To reset this bit, read ETH_MTLQICSR register to identify the interrupt cause and clear the source.
    #[inline(always)]
    pub fn q0is(&self) -> Q0IS_R {
        Q0IS_R::new((self.bits & 1) != 0)
    }
}
///Interrupt status Register
///
///This register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).
///
///For information about available fields see [mtlisr](index.html) module
pub struct MTLISR_SPEC;
impl crate::RegisterSpec for MTLISR_SPEC {
    type Ux = u32;
}
///`read()` method returns [mtlisr::R](R) reader structure
impl crate::Readable for MTLISR_SPEC {
    type Reader = R;
}
///`reset()` method sets MTLISR to value 0
impl crate::Resettable for MTLISR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
